<?php

use Illuminate\Database\Seeder;

class CurrenciesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('currencies')->delete();
        
        \DB::table('currencies')->insert(array (
            0 => 
            array (
                'id' => '1',
                'country' => 'Albania',
                'currency' => 'Lek',
                'symbol' => 'Lek',
                'codeiso' => 'ALL',
                'hexsymbol' => '4c, 65, 6b',
                'status' => 'active',
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            1 => 
            array (
                'id' => '2',
                'country' => 'Afghanistan',
                'currency' => 'Afghani',
                'symbol' => '؋',
                'codeiso' => 'AFN',
                'hexsymbol' => '60b',
                'status' => 'active',
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            2 => 
            array (
                'id' => '3',
                'country' => 'Argentina',
                'currency' => 'Peso',
                'symbol' => '$',
                'codeiso' => 'ARS',
                'hexsymbol' => '24',
                'status' => 'active',
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            3 => 
            array (
                'id' => '4',
                'country' => 'Aruba',
                'currency' => 'Guilder',
                'symbol' => 'ƒ',
                'codeiso' => 'AWG',
                'hexsymbol' => '192',
                'status' => 'active',
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            4 => 
            array (
                'id' => '5',
                'country' => 'Australia',
                'currency' => 'Dollar',
                'symbol' => '$',
                'codeiso' => 'AUD',
                'hexsymbol' => '24',
                'status' => 'active',
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            5 => 
            array (
                'id' => '6',
                'country' => 'Azerbaijan',
                'currency' => 'Manat',
                'symbol' => '₼',
                'codeiso' => 'AZN',
                'hexsymbol' => '20bc',
                'status' => 'active',
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            6 => 
            array (
                'id' => '7',
                'country' => 'Bahamas',
                'currency' => 'Dollar',
                'symbol' => '$',
                'codeiso' => 'BSD',
                'hexsymbol' => '24',
                'status' => 'active',
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            7 => 
            array (
                'id' => '8',
                'country' => 'Barbados',
                'currency' => 'Dollar',
                'symbol' => '$',
                'codeiso' => 'BBD',
                'hexsymbol' => '24',
                'status' => 'active',
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            8 => 
            array (
                'id' => '9',
                'country' => 'Belarus',
                'currency' => 'Ruble',
                'symbol' => 'p.',
                'codeiso' => 'BYR',
                'hexsymbol' => '70, 2e',
                'status' => 'active',
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            9 => 
            array (
                'id' => '10',
                'country' => 'Belize',
                'currency' => 'Dollar',
                'symbol' => 'BZ$',
                'codeiso' => 'BZD',
                'hexsymbol' => '42, 5a, 24',
                'status' => 'active',
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            10 => 
            array (
                'id' => '11',
                'country' => 'Bermuda',
                'currency' => 'Dollar',
                'symbol' => '$',
                'codeiso' => 'BMD',
                'hexsymbol' => '24',
                'status' => 'active',
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            11 => 
            array (
                'id' => '12',
                'country' => 'Bolivia',
                'currency' => 'Boliviano',
                'symbol' => '$b',
                'codeiso' => 'BOB',
                'hexsymbol' => '24, 62',
                'status' => 'active',
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            12 => 
            array (
                'id' => '13',
                'country' => 'Bosnia and Herzegovina',
                'currency' => 'Convertible Marka',
                'symbol' => 'KM',
                'codeiso' => 'BAM',
                'hexsymbol' => '4b, 4d',
                'status' => 'active',
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            13 => 
            array (
                'id' => '14',
                'country' => 'Botswana',
                'currency' => 'Pula',
                'symbol' => 'P',
                'codeiso' => 'BWP',
                'hexsymbol' => '50',
                'status' => 'active',
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            14 => 
            array (
                'id' => '15',
                'country' => 'Bulgaria',
                'currency' => 'Lev',
                'symbol' => 'лв',
                'codeiso' => 'BGN',
                'hexsymbol' => '43b, 432',
                'status' => 'active',
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            15 => 
            array (
                'id' => '16',
                'country' => 'Brazil',
                'currency' => 'Real',
                'symbol' => 'R$',
                'codeiso' => 'BRL',
                'hexsymbol' => '52, 24',
                'status' => 'active',
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            16 => 
            array (
                'id' => '17',
                'country' => 'Brunei',
                'currency' => 'Darussalam Dollar',
                'symbol' => '$',
                'codeiso' => 'BND',
                'hexsymbol' => '24',
                'status' => 'active',
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            17 => 
            array (
                'id' => '18',
                'country' => 'Cambodia',
                'currency' => 'Riel',
                'symbol' => '៛',
                'codeiso' => 'KHR',
                'hexsymbol' => '17db',
                'status' => 'active',
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            18 => 
            array (
                'id' => '19',
                'country' => 'Canada',
                'currency' => 'Dollar',
                'symbol' => '$',
                'codeiso' => 'CAD',
                'hexsymbol' => '24',
                'status' => 'active',
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            19 => 
            array (
                'id' => '20',
                'country' => 'Cayman',
                'currency' => 'Dollar',
                'symbol' => '$',
                'codeiso' => 'KYD',
                'hexsymbol' => '24',
                'status' => 'active',
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            20 => 
            array (
                'id' => '21',
                'country' => 'Chile',
                'currency' => 'Peso',
                'symbol' => '$',
                'codeiso' => 'CLP',
                'hexsymbol' => '24',
                'status' => 'active',
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            21 => 
            array (
                'id' => '22',
                'country' => 'China',
                'currency' => 'Yuan Renminbi',
                'symbol' => '¥',
                'codeiso' => 'CNY',
                'hexsymbol' => 'a5',
                'status' => 'active',
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            22 => 
            array (
                'id' => '23',
                'country' => 'Colombia',
                'currency' => 'Peso',
                'symbol' => '$',
                'codeiso' => 'COP',
                'hexsymbol' => '24',
                'status' => 'active',
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            23 => 
            array (
                'id' => '24',
                'country' => 'Costa Rica',
                'currency' => 'Colon',
                'symbol' => '₡',
                'codeiso' => 'CRC',
                'hexsymbol' => '20a1',
                'status' => 'active',
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            24 => 
            array (
                'id' => '25',
                'country' => 'Croatia',
                'currency' => 'Kuna',
                'symbol' => 'kn',
                'codeiso' => 'HRK',
                'hexsymbol' => '6b, 6e',
                'status' => 'active',
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            25 => 
            array (
                'id' => '26',
                'country' => 'Cuba',
                'currency' => 'Peso',
                'symbol' => '₱',
                'codeiso' => 'CUP',
                'hexsymbol' => '20b1',
                'status' => 'active',
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            26 => 
            array (
                'id' => '27',
                'country' => 'Czech Republic',
                'currency' => 'Koruna',
                'symbol' => 'Kč',
                'codeiso' => 'CZK',
                'hexsymbol' => '4b, 10d',
                'status' => 'active',
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            27 => 
            array (
                'id' => '28',
                'country' => 'Denmark',
                'currency' => 'Krone',
                'symbol' => 'kr',
                'codeiso' => 'DKK',
                'hexsymbol' => '6b, 72',
                'status' => 'active',
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            28 => 
            array (
                'id' => '29',
                'country' => 'Dominican Republic',
                'currency' => 'Peso',
                'symbol' => 'RD$',
                'codeiso' => 'DOP',
                'hexsymbol' => '52, 44, 24',
                'status' => 'active',
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            29 => 
            array (
                'id' => '30',
                'country' => 'East Caribbean',
                'currency' => 'Dollar',
                'symbol' => '$',
                'codeiso' => 'XCD',
                'hexsymbol' => '24',
                'status' => 'active',
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            30 => 
            array (
                'id' => '31',
                'country' => 'Egypt',
                'currency' => 'Pound',
                'symbol' => '£',
                'codeiso' => 'EGP',
                'hexsymbol' => 'a3',
                'status' => 'active',
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            31 => 
            array (
                'id' => '32',
                'country' => 'El Salvador',
                'currency' => 'Colon',
                'symbol' => '$',
                'codeiso' => 'SVC',
                'hexsymbol' => '24',
                'status' => 'active',
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            32 => 
            array (
                'id' => '33',
                'country' => 'Estonia',
                'currency' => 'Kroon',
                'symbol' => 'kr',
                'codeiso' => 'EEK',
                'hexsymbol' => '6b, 72',
                'status' => 'active',
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            33 => 
            array (
                'id' => '34',
                'country' => 'Euro Member',
                'currency' => 'Euro',
                'symbol' => '€',
                'codeiso' => 'EUR',
                'hexsymbol' => '20ac',
                'status' => 'active',
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            34 => 
            array (
                'id' => '35',
                'country' => 'Falkland Islands',
                'currency' => 'Pound',
                'symbol' => '£',
                'codeiso' => 'FKP',
                'hexsymbol' => 'a3',
                'status' => 'active',
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            35 => 
            array (
                'id' => '36',
                'country' => 'Fiji',
                'currency' => 'Dollar',
                'symbol' => '$',
                'codeiso' => 'FJD',
                'hexsymbol' => '24',
                'status' => 'active',
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            36 => 
            array (
                'id' => '37',
                'country' => 'Georgia',
                'currency' => 'Lari',
                'symbol' => '₾',
                'codeiso' => 'GEL',
                'hexsymbol' => '20be',
                'status' => 'active',
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            37 => 
            array (
                'id' => '38',
                'country' => 'Ghana',
                'currency' => 'Cedis',
                'symbol' => '¢',
                'codeiso' => 'GHC',
                'hexsymbol' => 'a2',
                'status' => 'active',
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            38 => 
            array (
                'id' => '39',
                'country' => 'Gibraltar',
                'currency' => 'Pound',
                'symbol' => '£',
                'codeiso' => 'GIP',
                'hexsymbol' => 'a3',
                'status' => 'active',
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            39 => 
            array (
                'id' => '40',
                'country' => 'Guatemala',
                'currency' => 'Quetzal',
                'symbol' => 'Q',
                'codeiso' => 'GTQ',
                'hexsymbol' => '51',
                'status' => 'active',
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            40 => 
            array (
                'id' => '41',
                'country' => 'Guernsey',
                'currency' => 'Pound',
                'symbol' => '£',
                'codeiso' => 'GGP',
                'hexsymbol' => 'a3',
                'status' => 'active',
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            41 => 
            array (
                'id' => '42',
                'country' => 'Guyana',
                'currency' => 'Dollar',
                'symbol' => '$',
                'codeiso' => 'GYD',
                'hexsymbol' => '24',
                'status' => 'active',
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            42 => 
            array (
                'id' => '43',
                'country' => 'Honduras',
                'currency' => 'Lempira',
                'symbol' => 'L',
                'codeiso' => 'HNL',
                'hexsymbol' => '4c',
                'status' => 'active',
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            43 => 
            array (
                'id' => '44',
                'country' => 'Hong Kong',
                'currency' => 'Dollar',
                'symbol' => '$',
                'codeiso' => 'HKD',
                'hexsymbol' => '24',
                'status' => 'active',
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            44 => 
            array (
                'id' => '45',
                'country' => 'Hungary',
                'currency' => 'Forint',
                'symbol' => 'Ft',
                'codeiso' => 'HUF',
                'hexsymbol' => '46, 74',
                'status' => 'active',
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            45 => 
            array (
                'id' => '46',
                'country' => 'Iceland',
                'currency' => 'Krona',
                'symbol' => 'kr',
                'codeiso' => 'ISK',
                'hexsymbol' => '6b, 72',
                'status' => 'active',
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            46 => 
            array (
                'id' => '47',
                'country' => 'India',
                'currency' => 'Rupee',
                'symbol' => '₹',
                'codeiso' => 'INR',
                'hexsymbol' => '20B9',
                'status' => 'active',
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            47 => 
            array (
                'id' => '48',
                'country' => 'Indonesia',
                'currency' => 'Rupiah',
                'symbol' => 'Rp',
                'codeiso' => 'IDR',
                'hexsymbol' => '52, 70',
                'status' => 'active',
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            48 => 
            array (
                'id' => '49',
                'country' => 'Iran',
                'currency' => 'Rial',
                'symbol' => '﷼',
                'codeiso' => 'IRR',
                'hexsymbol' => 'fdfc',
                'status' => 'active',
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            49 => 
            array (
                'id' => '50',
                'country' => 'Isle of Man',
                'currency' => 'Pound',
                'symbol' => '£',
                'codeiso' => 'IMP',
                'hexsymbol' => 'a3',
                'status' => 'active',
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            50 => 
            array (
                'id' => '51',
                'country' => 'Israel',
                'currency' => 'Shekel',
                'symbol' => '₪',
                'codeiso' => 'ILS',
                'hexsymbol' => '20aa',
                'status' => 'active',
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            51 => 
            array (
                'id' => '52',
                'country' => 'Jamaica',
                'currency' => 'Dollar',
                'symbol' => 'J$',
                'codeiso' => 'JMD',
                'hexsymbol' => '4a, 24',
                'status' => 'active',
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            52 => 
            array (
                'id' => '53',
                'country' => 'Japan',
                'currency' => 'Yen',
                'symbol' => '¥',
                'codeiso' => 'JPY',
                'hexsymbol' => 'a5',
                'status' => 'active',
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            53 => 
            array (
                'id' => '54',
                'country' => 'Jersey',
                'currency' => 'Pound',
                'symbol' => '£',
                'codeiso' => 'JEP',
                'hexsymbol' => 'a3',
                'status' => 'active',
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            54 => 
            array (
                'id' => '55',
                'country' => 'Kazakhstan',
                'currency' => 'Tenge',
                'symbol' => 'лв',
                'codeiso' => 'KZT',
                'hexsymbol' => '43b, 432',
                'status' => 'active',
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            55 => 
            array (
                'id' => '56',
            'country' => 'Korea (North)',
                'currency' => 'Won',
                'symbol' => '₩',
                'codeiso' => 'KPW',
                'hexsymbol' => '20a9',
                'status' => 'active',
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            56 => 
            array (
                'id' => '57',
            'country' => 'Korea (South)',
                'currency' => 'Won',
                'symbol' => '₩',
                'codeiso' => 'KRW',
                'hexsymbol' => '20a9',
                'status' => 'active',
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            57 => 
            array (
                'id' => '58',
                'country' => 'Kyrgyzstan',
                'currency' => 'Som',
                'symbol' => 'лв',
                'codeiso' => 'KGS',
                'hexsymbol' => '43b, 432',
                'status' => 'active',
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            58 => 
            array (
                'id' => '59',
                'country' => 'Laos',
                'currency' => 'Kip',
                'symbol' => '₭',
                'codeiso' => 'LAK',
                'hexsymbol' => '20ad',
                'status' => 'active',
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            59 => 
            array (
                'id' => '60',
                'country' => 'Latvia',
                'currency' => 'Lat',
                'symbol' => 'Ls',
                'codeiso' => 'LVL',
                'hexsymbol' => '4c, 73',
                'status' => 'active',
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            60 => 
            array (
                'id' => '61',
                'country' => 'Lebanon',
                'currency' => 'Pound',
                'symbol' => '£',
                'codeiso' => 'LBP',
                'hexsymbol' => 'a3',
                'status' => 'active',
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            61 => 
            array (
                'id' => '62',
                'country' => 'Liberia',
                'currency' => 'Dollar',
                'symbol' => '$',
                'codeiso' => 'LRD',
                'hexsymbol' => '24',
                'status' => 'active',
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            62 => 
            array (
                'id' => '63',
                'country' => 'Lithuania',
                'currency' => 'Litas',
                'symbol' => 'Lt',
                'codeiso' => 'LTL',
                'hexsymbol' => '4c, 74',
                'status' => 'active',
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            63 => 
            array (
                'id' => '64',
                'country' => 'Macedonia',
                'currency' => 'Denar',
                'symbol' => 'ден',
                'codeiso' => 'MKD',
                'hexsymbol' => '434, 435, 43d',
                'status' => 'active',
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            64 => 
            array (
                'id' => '65',
                'country' => 'Malaysia',
                'currency' => 'Ringgit',
                'symbol' => 'RM',
                'codeiso' => 'MYR',
                'hexsymbol' => '52, 4d',
                'status' => 'active',
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            65 => 
            array (
                'id' => '66',
                'country' => 'Mauritius',
                'currency' => 'Rupee',
                'symbol' => '₨',
                'codeiso' => 'MUR',
                'hexsymbol' => '20a8',
                'status' => 'active',
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            66 => 
            array (
                'id' => '67',
                'country' => 'Mexico',
                'currency' => 'Peso',
                'symbol' => '$',
                'codeiso' => 'MXN',
                'hexsymbol' => '24',
                'status' => 'active',
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            67 => 
            array (
                'id' => '68',
                'country' => 'Mongolia',
                'currency' => 'Tughrik',
                'symbol' => '₮',
                'codeiso' => 'MNT',
                'hexsymbol' => '20ae',
                'status' => 'active',
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            68 => 
            array (
                'id' => '69',
                'country' => 'Mozambique',
                'currency' => 'Metical',
                'symbol' => 'MT',
                'codeiso' => 'MZN',
                'hexsymbol' => '4d, 54',
                'status' => 'active',
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            69 => 
            array (
                'id' => '70',
                'country' => 'Namibia',
                'currency' => 'Dollar',
                'symbol' => '$',
                'codeiso' => 'NAD',
                'hexsymbol' => '24',
                'status' => 'active',
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            70 => 
            array (
                'id' => '71',
                'country' => 'Nepal',
                'currency' => 'Rupee',
                'symbol' => '₨',
                'codeiso' => 'NPR',
                'hexsymbol' => '20a8',
                'status' => 'active',
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            71 => 
            array (
                'id' => '72',
                'country' => 'Netherlands',
                'currency' => 'Antilles Guilder',
                'symbol' => 'ƒ',
                'codeiso' => 'ANG',
                'hexsymbol' => '192',
                'status' => 'active',
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            72 => 
            array (
                'id' => '73',
                'country' => 'New Zealand',
                'currency' => 'Dollar',
                'symbol' => '$',
                'codeiso' => 'NZD',
                'hexsymbol' => '24',
                'status' => 'active',
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            73 => 
            array (
                'id' => '74',
                'country' => 'Nicaragua',
                'currency' => 'Cordoba',
                'symbol' => 'C$',
                'codeiso' => 'NIO',
                'hexsymbol' => '43, 24',
                'status' => 'active',
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            74 => 
            array (
                'id' => '75',
                'country' => 'Nigeria',
                'currency' => 'Naira',
                'symbol' => '₦',
                'codeiso' => 'NGN',
                'hexsymbol' => '20a6',
                'status' => 'active',
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            75 => 
            array (
                'id' => '76',
                'country' => 'Norway',
                'currency' => 'Krone',
                'symbol' => 'kr',
                'codeiso' => 'NOK',
                'hexsymbol' => '6b, 72',
                'status' => 'active',
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            76 => 
            array (
                'id' => '77',
                'country' => 'Oman',
                'currency' => 'Rial',
                'symbol' => '﷼',
                'codeiso' => 'OMR',
                'hexsymbol' => 'fdfc',
                'status' => 'active',
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            77 => 
            array (
                'id' => '78',
                'country' => 'Pakistan',
                'currency' => 'Rupee',
                'symbol' => '₨',
                'codeiso' => 'PKR',
                'hexsymbol' => '20a8',
                'status' => 'active',
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            78 => 
            array (
                'id' => '79',
                'country' => 'Panama',
                'currency' => 'Balboa',
                'symbol' => 'B/.',
                'codeiso' => 'PAB',
                'hexsymbol' => '42, 2f, 2e',
                'status' => 'active',
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            79 => 
            array (
                'id' => '80',
                'country' => 'Paraguay',
                'currency' => 'Guarani',
                'symbol' => 'Gs',
                'codeiso' => 'PYG',
                'hexsymbol' => '47, 73',
                'status' => 'active',
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            80 => 
            array (
                'id' => '81',
                'country' => 'Peru',
                'currency' => 'Nuevo Sol',
                'symbol' => 'S/.',
                'codeiso' => 'PEN',
                'hexsymbol' => '53, 2f, 2e',
                'status' => 'active',
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            81 => 
            array (
                'id' => '82',
                'country' => 'Philippines',
                'currency' => 'Peso',
                'symbol' => '₱',
                'codeiso' => 'PHP',
                'hexsymbol' => '20b1',
                'status' => 'active',
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            82 => 
            array (
                'id' => '83',
                'country' => 'Poland',
                'currency' => 'Zloty',
                'symbol' => 'zł',
                'codeiso' => 'PLN',
                'hexsymbol' => '7a, 142',
                'status' => 'active',
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            83 => 
            array (
                'id' => '84',
                'country' => 'Qatar',
                'currency' => 'Riyal',
                'symbol' => '﷼',
                'codeiso' => 'QAR',
                'hexsymbol' => 'fdfc',
                'status' => 'active',
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            84 => 
            array (
                'id' => '85',
                'country' => 'Romania',
                'currency' => 'New Leu',
                'symbol' => 'lei',
                'codeiso' => 'RON',
                'hexsymbol' => '6c, 65, 69',
                'status' => 'active',
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            85 => 
            array (
                'id' => '86',
                'country' => 'Russia',
                'currency' => 'Ruble',
                'symbol' => '₽',
                'codeiso' => 'RUB',
                'hexsymbol' => '20bd',
                'status' => 'active',
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            86 => 
            array (
                'id' => '87',
                'country' => 'Saint Helena',
                'currency' => 'Pound',
                'symbol' => '£',
                'codeiso' => 'SHP',
                'hexsymbol' => 'a3',
                'status' => 'active',
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            87 => 
            array (
                'id' => '88',
                'country' => 'Saudi Arabia',
                'currency' => 'Riyal',
                'symbol' => '﷼',
                'codeiso' => 'SAR',
                'hexsymbol' => 'fdfc',
                'status' => 'active',
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            88 => 
            array (
                'id' => '89',
                'country' => 'Serbia',
                'currency' => 'Dinar',
                'symbol' => 'Дин.',
                'codeiso' => 'RSD',
                'hexsymbol' => '414, 438, 43d, 2e',
                'status' => 'active',
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            89 => 
            array (
                'id' => '90',
                'country' => 'Seychelles',
                'currency' => 'Rupee',
                'symbol' => '₨',
                'codeiso' => 'SCR',
                'hexsymbol' => '20a8',
                'status' => 'active',
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            90 => 
            array (
                'id' => '91',
                'country' => 'Singapore',
                'currency' => 'Dollar',
                'symbol' => '$',
                'codeiso' => 'SGD',
                'hexsymbol' => '24',
                'status' => 'active',
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            91 => 
            array (
                'id' => '92',
                'country' => 'Solomon Islands',
                'currency' => 'Dollar',
                'symbol' => '$',
                'codeiso' => 'SBD',
                'hexsymbol' => '24',
                'status' => 'active',
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            92 => 
            array (
                'id' => '93',
                'country' => 'Somalia',
                'currency' => 'Shilling',
                'symbol' => 'S',
                'codeiso' => 'SOS',
                'hexsymbol' => '53',
                'status' => 'active',
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            93 => 
            array (
                'id' => '94',
                'country' => 'South Africa',
                'currency' => 'Rand',
                'symbol' => 'S',
                'codeiso' => 'ZAR',
                'hexsymbol' => '52',
                'status' => 'active',
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            94 => 
            array (
                'id' => '95',
                'country' => 'Sri Lanka',
                'currency' => 'Rupee',
                'symbol' => '₨',
                'codeiso' => 'LKR',
                'hexsymbol' => '20a8',
                'status' => 'active',
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            95 => 
            array (
                'id' => '96',
                'country' => 'Sweden',
                'currency' => 'Krona',
                'symbol' => 'kr',
                'codeiso' => 'SEK',
                'hexsymbol' => '6b, 72',
                'status' => 'active',
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            96 => 
            array (
                'id' => '97',
                'country' => 'Switzerland',
                'currency' => 'Franc',
                'symbol' => 'CHF',
                'codeiso' => 'CHF',
                'hexsymbol' => '43, 48, 46',
                'status' => 'active',
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            97 => 
            array (
                'id' => '98',
                'country' => 'Suriname',
                'currency' => 'Dollar',
                'symbol' => '$',
                'codeiso' => 'SRD',
                'hexsymbol' => '24',
                'status' => 'active',
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            98 => 
            array (
                'id' => '99',
                'country' => 'Syria',
                'currency' => 'Pound',
                'symbol' => '£',
                'codeiso' => 'SYP',
                'hexsymbol' => 'a3',
                'status' => 'active',
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            99 => 
            array (
                'id' => '100',
                'country' => 'Taiwan',
                'currency' => 'New Dollar',
                'symbol' => 'NT$',
                'codeiso' => 'TWD',
                'hexsymbol' => '4e, 54, 24',
                'status' => 'active',
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            100 => 
            array (
                'id' => '101',
                'country' => 'Thailand',
                'currency' => 'Baht',
                'symbol' => '฿',
                'codeiso' => 'THB',
                'hexsymbol' => 'e3f',
                'status' => 'active',
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            101 => 
            array (
                'id' => '102',
                'country' => 'Trinidad and Tobago',
                'currency' => 'Dollar',
                'symbol' => 'TT$',
                'codeiso' => 'TTD',
                'hexsymbol' => '54, 54, 24',
                'status' => 'active',
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            102 => 
            array (
                'id' => '103',
                'country' => 'Turkey',
                'currency' => 'Lira',
                'symbol' => '₺',
                'codeiso' => 'TRL',
                'hexsymbol' => '20ba',
                'status' => 'active',
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            103 => 
            array (
                'id' => '104',
                'country' => 'Tuvalu',
                'currency' => 'Dollar',
                'symbol' => '$',
                'codeiso' => 'TVD',
                'hexsymbol' => '24',
                'status' => 'active',
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            104 => 
            array (
                'id' => '105',
                'country' => 'Ukraine',
                'currency' => 'Hryvna',
                'symbol' => '₴',
                'codeiso' => 'UAH',
                'hexsymbol' => '20b4',
                'status' => 'active',
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            105 => 
            array (
                'id' => '106',
                'country' => 'United Kingdom',
                'currency' => 'Pound',
                'symbol' => '£',
                'codeiso' => 'GBP',
                'hexsymbol' => 'a3',
                'status' => 'active',
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            106 => 
            array (
                'id' => '107',
                'country' => 'United States',
                'currency' => 'Dollar',
                'symbol' => '$',
                'codeiso' => 'USD',
                'hexsymbol' => '24',
                'status' => 'active',
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            107 => 
            array (
                'id' => '108',
                'country' => 'Uruguay',
                'currency' => 'Peso',
                'symbol' => '$U',
                'codeiso' => 'UYU',
                'hexsymbol' => '24, 55',
                'status' => 'active',
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            108 => 
            array (
                'id' => '109',
                'country' => 'Uzbekistan',
                'currency' => 'Som',
                'symbol' => 'лв',
                'codeiso' => 'UZS',
                'hexsymbol' => '43b, 432',
                'status' => 'active',
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            109 => 
            array (
                'id' => '110',
                'country' => 'Venezuela',
                'currency' => 'Bolivar Fuerte',
                'symbol' => 'Bs',
                'codeiso' => 'VEF',
                'hexsymbol' => '42, 73',
                'status' => 'active',
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            110 => 
            array (
                'id' => '111',
                'country' => 'Viet Nam',
                'currency' => 'Dong',
                'symbol' => '₫',
                'codeiso' => 'VND',
                'hexsymbol' => '20ab',
                'status' => 'active',
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            111 => 
            array (
                'id' => '112',
                'country' => 'Yemen',
                'currency' => 'Rial',
                'symbol' => '﷼',
                'codeiso' => 'YER',
                'hexsymbol' => 'fdfc',
                'status' => 'active',
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            112 => 
            array (
                'id' => '113',
                'country' => 'Zimbabwe',
                'currency' => 'Dollar',
                'symbol' => 'Z$',
                'codeiso' => 'ZWD',
                'hexsymbol' => '5a, 24',
                'status' => 'active',
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
        ));
        
        
    }
}
